// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqhxsnbfverpingpkthy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxaHhzbmJmdmVycGluZ3BrdGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDk5NjIsImV4cCI6MjA2NjY4NTk2Mn0.Vbnxt13xA3yGfHJHXJNckmoVrYeaRUbXgpNodWm7vCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);